// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEZl7s0vx62jhPUdW67-JAs6Y2SErg2hM',
    appId: '1:158240125685:android:245a0de384a17a40c80bbc',
    messagingSenderId: '158240125685',
    projectId: 'libras-app-7e067',
    databaseURL: 'https://libras-app-7e067-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'libras-app-7e067.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrvjHzdiSxDbWHhjb7SLwxK4GvCbHmlIc',
    appId: '1:158240125685:ios:bc93f7d7d35757bbc80bbc',
    messagingSenderId: '158240125685',
    projectId: 'libras-app-7e067',
    databaseURL: 'https://libras-app-7e067-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'libras-app-7e067.appspot.com',
    iosClientId: '158240125685-t6lkim2isfg7u2k6kpgufchsepjnlmgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.libasApp',
  );
}
